### ISSUE TITLE
React native 0.59.9引发手机发烫问题解决思路

### ISSUE THREAD

**Issue by yyhinbeijing** [zhangferry/iOSWeeklyLearning#101]
## bug出现的现象是什么样的？
rn页面放置很久，或者反复操作不同的rn页面，手机会变得很烫，并且不会自动降温，要杀掉进程才会降温，版本是0.59.9，几乎不同手机不同手机系统版本均遇到了这个问题.

## 是如何解决的？
通过不断的注释代码，看监听到的CPU的占有量，以下是分类的逻辑。
(零)原生的 7.2%
(一)无网络无Flatlist：7.2%同原生  X上面

(二)发热不影响cpu，降不下来怎么办，重新启动

(三)首页测试
网络 + FlatList ：100%+

(四)无网络 + FlatList: 2.5-40%，能降低，

(五)网络 + 无FlatList:100%+，不会降低至小于100 ，最高188
(1)去掉loading 2.6% — 30%，会降低

(六)网络和flatlist全部放开，只关闭loading  最低7.2%，能降低  最高63%

(七)所有的代码去掉放开，只关闭loading

去掉loading 2.6% — 30%，会降低

我们首先是发现网络占用CPU很高，然后网络注释掉RNLoading(我们自写的loading动画),发现内存占用不高了。
就断定是RNLoading问题，原因是：我们每次点击tab都会加载loading，而loading又是动画，这样大量的动画引发内存问题。

## bug引发的反思？（如果有的话）bug隐含了什么知识点
算法和生活
我们生活中，为什么要整理呢，从算法角度讲，就是降低时间复杂度。
寻找错误也能用算法，就像上面的寻找问题，通过不断的试，类似二分法。
算法就是我们的聪明才智啊。

**Comment by zhangferry** [comment]
@yyhinbeijing 本期内容已够，下期将采用本Tips
