### ISSUE TITLE
周报第三期 博客推荐汇总

### ISSUE THREAD

**Issue by zhangferry** [zhangferry/iOSWeeklyLearning#12]
这个页面可以填写推荐的博客

**Comment by zhangferry** [comment]
[iOS性能优化实践：头条抖音如何实现OOM崩溃率下降50%+](https://mp.weixin.qq.com/s/4-4M9E8NziAgshlwB7Sc6g)

**Comment by liumenghua** [comment]
[效率提升50%，移动端UI自助验收在爱奇艺的探索与实践](https://mp.weixin.qq.com/s/K9p8986Gq1DoQ1fUYivPrg)

**Comment by liumenghua** [comment]
[磁盘I/O那些事](https://tech.meituan.com/2017/05/19/about-desk-io.html)

**Comment by loveuqian** [comment]
Xcode 12.3 模拟器变黄的问题


https://stackoverflow.com/questions/65299337/xcode-12-3-ios-14-3-simulators-yellow-dock-yellow-translucent-issues


https://medium.com/%E5%BD%BC%E5%BE%97%E6%BD%98%E7%9A%84-swift-ios-app-%E9%96%8B%E7%99%BC%E5%95%8F%E9%A1%8C%E8%A7%A3%E7%AD%94%E9%9B%86/xcode-12-3-%E6%A8%A1%E6%93%AC%E5%99%A8%E7%9A%84%E9%BB%83%E8%89%B2%E5%95%8F%E9%A1%8C-d99ab11da28c

**Comment by zhangferry** [comment]
@loveuqian 这个问题可以新建一个bug的issue，还有不能只贴链接哦，需要简单总结下问题和解决步骤。

**Comment by loveuqian** [comment]
> @loveuqian 这个问题可以新建一个bug的issue，还有不能只贴链接哦，需要简单总结下问题和解决步骤。

只是刚好更新了 Xcode 遇到了问题，又刚好看到这个仓库和 issues，所以就刚好回复了一下

**Comment by zhangferry** [comment]
@loveuqian 解决思路还在的话，可以共享出来嘛
