### ISSUE TITLE
@property的修饰符有哪些？

### ISSUE THREAD

**Issue by opooc** [zhangferry/iOSWeeklyLearning#122]
@property的修饰符有哪些？分别介绍下功能和使用场景?

一. 有以下几种修饰符
原子性：atomic，nonatiomic
读写语义：readwrite、readonly、getter、setter
内存管理：assign、weak、retain、strong、copy、unsafe_unretained

二. 分析
atomic/nonatomic：
1. 使用atomic后，不能再重写setter和getter，否则会产生编译错误
2.若不指定原子性相关的修饰符，默认为atomic，会对属性的setter方法加锁
3.开发中，一般使用nonatomic，提高多线程访问的性能

readonly/readwrite:
1.readonly表示只读，也就是修饰的变量只有get方法，没有set方法
2.readwrite既有get，也有set方法
3.补充，使用getter =<> ,setter=<xx>可以选择性地在括号里直接存取方法的方法名.

assign/weak:
assign直接赋值，不会增加对象的引用计数，主要用于修饰非OC类型，用于NSInteger/Boolean等基础数据类型和C语言数据类型.或修饰对指针的弱引用；也可以用于修饰OC对象类型，但是assign修饰的对象在该对象释放后，其指针依然存在，不会被置为nil，访问的时候可能会出现崩溃
weak:修饰弱引用，不增加引用对象的引用计数，主要可以用于避免循环引用，功能上和assign一样简单，但不同的是，用weak修饰的对象的时候会自动将指针置位nil,
一般自己写UI控件都是使用weak，xib也使用Weak

retain/strong：对对象进行强引用，
1、retain是MRC下，赋值的时候，判断参数地址和实例变量地址不同的话，移除旧对象，新对象的引用计数+1，给到变量；别的对象对其做引用的时候，直接引用计数+1
2.strong的底层跟retain一样，不过是运行在ARC下
3.不过在声明Block时，使用strong和retain会有截然不同的效果。strong会等于copy，而retain竟然等于assign。（记得和Block打通） 

copy：
1.一般copy关键字用在NSString、NSArray、NSDictionary等属性字段的修饰符，这样外面传可变或者不可变得对象，内部留下的都是不可变对象
2.对于不可变对象，进行浅拷贝，对于可变对象进行深拷贝
3.copy后的对象都是不可变得对象
4.属性赋值的时候底层先将旧的release,然后 将参数copy后给当前变量,参数引用计数不变

unsafe_unretained：就是弱化版本的assign，用来修饰对象，会出现野指针问题

**Comment by zhangferry** [comment]
@all-contributors please add @opooc  for blog
