### ISSUE TITLE
Core Data with CloudKit —— 创建与多个iCloud用户共享数据的应用

### ISSUE THREAD

**Issue by fatbobman** [zhangferry/iOSWeeklyLearning#159]
包括图书、音视频等形式，如果有pdf、epub等格式的电子书，不存在版权的前提下可以以附件形式添加

## 享的内容

https://mp.weixin.qq.com/s?__biz=MzU1Njg1NDg5NQ==&mid=2247483952&idx=1&sn=5deee14aa263842b8b632dd95f3741a1&chksm=fc3ff930cb487026879d50835f76da85239064137958b956509762c7d3b98e970f60b3be8555&token=1363363513&lang=zh_CN#rd

相信应该有不少的朋友都使用过iOS自带的共享相簿或者共享备忘录功能。这些功能的实现都是基于几年前苹果推出的CloudKit共享数据API。在WWDC 2021中，苹果将该功能集成到Core Data with CloudKit之中，我们终于可以在使用少量CloudKit API的情况下，用Core Data的操作方式创建具有同样功能的应用程序了。

## 推荐理由

Core Data with Cloud 系列文章（1-6）的最新一篇。
详细说明了如何使用Core Data创建共享数据的应用程序，包含完整原创范例代码。

**Comment by zhangferry** [comment]
感谢推荐
