### ISSUE TITLE
摸鱼周报第六期内容推荐

### ISSUE THREAD

**Issue by zhangferry** [zhangferry/iOSWeeklyLearning#16]
想要推荐的文章可以写到这个issue里

**Comment by HighwayLaw** [comment]
## 链接

[函数节流（Throttle）和防抖（Debounce）解析及其iOS实现](https://juejin.cn/post/6933952291142074376)

## 理由

对于连续调用的函数，尤其是触发频率密集、目标函数涉及大量计算时，恰当使用Throttle和Debounce可以有效提升性能及系统稳定性。

作者详细阐述了Throttle和Debounce的概念及二者间的区别，同时封装开源了HWThrottle库，借鉴了Lodash的接口及实现方式，该库有以下特点：
1）未使用任何runtime API，全部由顶层API实现；
2）每个业务场景需要使用者自己定义一个实例对象，自行管理生命周期，旨在把对项目的影响控制在最小范围；
3）区分Throttle和Debounce，提供Leading和Trailing选项。

**Comment by zhangferry** [comment]
@HighwayLaw  挺不错的，我转载你这篇文章吧，可以不

**Comment by HighwayLaw** [comment]
> @HighwayLaw 挺不错的，我转载你这篇文章吧，可以不

OK 😄

**Comment by zhangferry** [comment]
> > @HighwayLaw 挺不错的，我转载你这篇文章吧，可以不
> 
> OK 😄

👍

**Comment by jcexk** [comment]
## 推荐一款Provisioning Profile管理工具 ProfilesManager
一款Provisioning Profile管理工具
#

背景：下午同事更新了下profile，也已经导入到了Xcode中，可是死活就是运行不起来，我建议他把profile缓存给清一下，看他准备百度profile路径时，在我的建议之下，同事安装了ProfilesManager，用起来了之后：“嚯，好家伙，本地居然有7、80个profile文件”，皇天不负有心人，努力的结果就是项目还是没有跑起来😅。
### 正文
工人云：工欲善其事必先利其器。熟练运用各种快捷键和第三方管理工具也能提升工作效率。接下来向大家推荐一款Provisioning Profile管理工具：ProfilesManager。

**ProfilesManager特点如下：**

1. 方便快捷：支持查看电脑中所有的描述文件
2. 一目了然：通过美化描述文件名，不再是难以辨认的'uuid+ext'格式
3. 功能强大：支持查看ipa中描述文件和info.plist信息
4. 结构清晰：通过树状结构查看描述文件包含的详细信息，如：创建时间、失效时间和包含的移动设备信息等
<img width="856" alt="image" src="https://user-images.githubusercontent.com/28210342/111930937-09be0200-8af5-11eb-9d1c-c30bd2f2559b.png">

5. 免费使用：而在App Store上类似功能的软件居然还要收费？？？
6. 可排序和过滤：通过关键词筛选过滤找到想要的文件，也可以通过头部标签排序文件
<img width="1214" alt="image" src="https://user-images.githubusercontent.com/28210342/111819633-8a290b00-891b-11eb-86fb-9f343acfb938.png">

[话不多说，直接上菜](https://github.com/shaojiankui/ProfilesManager)
手动复制：https://github.com/shaojiankui/ProfilesManager
祝诸君一帆风顺前程似锦！

**Comment by zhangferry** [comment]
已采纳
