### ISSUE TITLE
文件操作效率工具 - Dropshelf

### ISSUE THREAD

**Issue by iOSleep** [zhangferry/iOSWeeklyLearning#194]
## 它叫什么名字，简单介绍
**Dropshelf** 是一款Mac OS下的拖拽效率应用。它提供了一个可以吸附在屏幕边缘的Dock，你可以拖拽任何东西「图片、文件、文字、链接...」暂存到Dock中，方便你在其他App中来使用。 [介绍链接](https://zhuanlan.zhihu.com/p/19692341)
## 是否付费（如果付费的话标下价格）
之前付费但是目前下架了，可以使用作者提供的链接免费使用。
## 下载地址，提供正版下载地址（个别大型的收入网站也行，不要使用网盘）
[下载地址](https://pilotmoon.com/downloads/beta/Dropshelf-build-1729.zip)
[app首页](https://pilotmoon.com/dropshelf/)

**Comment by zhangferry** [comment]
感谢推荐，下期内容会采纳

**Comment by zhangferry** [comment]
已采纳
