### ISSUE TITLE
swift调用runtime，clourse传参导致闪退问题

### ISSUE THREAD

**Issue by weiminghuaa** [zhangferry/iOSWeeklyLearning#20]
## bug出现的现象是什么样的？

原生和web、小程序、flutter等等交互时，传递给原生的是方法名和数据，所以经常需要写方法转发函数，用到performSelector。在OC时，传递block没问题，Swift就不行，可能在performSelector闪退，也可能在block执行的地方闪退

![21617687306_ pic_hd](https://user-images.githubusercontent.com/2723525/113679539-738ffb80-96f2-11eb-80e6-4bcdf86e7d78.jpg)

![271617690340_ pic_hd](https://user-images.githubusercontent.com/2723525/113679460-5bb87780-96f2-11eb-9afd-9864e239ff38.jpg)

## 是如何解决的？
swift调用performSelector传参之前，将swift的clourse，显示的转换为oc的block。同时，打印通过object_getClass获取到的类型，确实不一样
```
let name: AnyClass! = object_getClass(callback)
print(name)// Optional(__SwiftValue)

// 关键代码
let block : @convention(block) (Any, Bool) -> () = callback

let name2: AnyClass! = object_getClass(block)
print(name2)// Optional(__NSMallocBlock__)
```
https://stackoverflow.com/questions/26374792/difference-between-block-objective-c-and-closure-swift-in-ios
## bug引发的反思？（如果有的话）bug隐含了什么知识点
知识点太偏了，难搞。

解题思路记一下：（真正的技术群很关键，讨论才有灵感）
1、刚开始，完全不知所措
2、在开发者群里好友的建议下，分别写了oc和swift的demo，确认oc没问题，swift有问题
3、基于第二点的结果，猜测，swift的closure和oc的block，虽然都是闭包，但毕竟是不同语言，应该是不同实现，大多数情况在项目中通用，但是具体到这里，swift调oc的runtime去传参，把closure传过去，就出问题，无法copy，closure直接在函数结束时销毁了
4、尝试了解block的底层，并了解closure和block的差异，最终找到了可以显示转换的方法

**Comment by zhangferry** [comment]
已采纳
