### ISSUE TITLE
《虾票票》入门iOS系列汇总（附源码！）

### ISSUE THREAD

**Issue by doubleLLL3** [zhangferry/iOSWeeklyLearning#260]
## 文章标题、著名出处和作者
《虾票票》入门iOS系列汇总（附源码！）
出处：公众号 Bo2SS

## 文章链接
https://mp.weixin.qq.com/s?__biz=Mzg3MjcxNzUxOQ==&mid=2247484917&idx=1&sn=5a5ae3592f664dbd550e3a4b900a0377&chksm=ceea4855f99dc143cf03f11ba0e8722a7d52870e3d780e44794c5017aa2bb5169ede003d3c99&token=2111740385&lang=zh_CN#rd

## 推荐理由（如果没有可以摘抄文章内一段重要的话）
这是一个系列，讲解详细，精心排版；作者也是刚从小白入门，对新人友好

**Comment by zhangferry** [comment]
暂不录用
