### ISSUE TITLE
网址似乎证书无效？https://www.zhangferry.com

### ISSUE THREAD

**Issue by Howard-Wang-Hao** [zhangferry/iOSWeeklyLearning#265]
## bug出现的现象是什么样的？
任意浏览器，新打开https://www.zhangferry.com，报网站不安全的提示，阻止访问。

## 是如何解决的？
只能点击选择不安全的链接；但Reeder等阅读器似乎就没那么幸运了，直接无法订阅该地址。
另，似乎只有这个地址是最新内容，【掘金社区】那里不更新了？

**Comment by Howard-Wang-Hao** [comment]
<img width="260" alt="image" src="https://user-images.githubusercontent.com/15625147/170873305-cb96cb35-f27c-4fa4-91df-2fc7a5de4b0b.png">

**Comment by Howard-Wang-Hao** [comment]
还有https://zhangferry.com/atom.xml，404了哦

**Comment by zhangferry** [comment]
1、不安全的链接，提示截图能发个吗？该问题我这没有出现，这时的https证书能否正常查看？
2、站点进行了更新，rss受到了影响，这块晚些上线
3、内容更新及时程度，博客 > 公众号 > 掘金

**Comment by zhangferry** [comment]
@Howard-Wang-Hao RSS问题修复了，可以再试下

**Comment by Howard-Wang-Hao** [comment]
> 
👍🏻 好的

**Comment by Howard-Wang-Hao** [comment]
> 1、不安全的链接，提示截图能发个吗？该问题我这没有出现，这时的https证书能否正常查看？ 2、站点进行了更新，rss受到了影响，这块晚些上线 3、内容更新及时程度，博客 > 公众号 > 掘金

补充：
<img width="394" alt="image" src="https://user-images.githubusercontent.com/15625147/170913587-b34eda54-1112-475f-af59-4e3bafee18c0.png">

**Comment by zhangferry** [comment]
> > 1、不安全的链接，提示截图能发个吗？该问题我这没有出现，这时的https证书能否正常查看？ 2、站点进行了更新，rss受到了影响，这块晚些上线 3、内容更新及时程度，博客 > 公众号 > 掘金
> 
> 补充： <img alt="image" width="394" src="https://user-images.githubusercontent.com/15625147/170913587-b34eda54-1112-475f-af59-4e3bafee18c0.png">

这是一个重定向问题，zhangferry.com和www.zhangferry.com这两个域名用的证书不同，带www那个域名证书过期了。现在会统一重定向到zhangferry.com，可以再试下
