### ISSUE TITLE
iOS灵动岛【电商商品秒杀】开发实践

### ISSUE THREAD

**Issue by erduoniba** [zhangferry/iOSWeeklyLearning#303]
## 文章标题、著名出处和作者
iOS灵动岛【电商商品秒杀】开发实践
邓立兵，京喜App端iOS开发者

## 文章链接
https://juejin.cn/post/7153236337074634788

## 推荐理由（如果没有可以摘抄文章内一段重要的话）
iOS灵动岛【电商商品秒杀】开发实践，详细讲解了灵动岛的基本概念、开发基本要素及细节。Demo中展示了主工程和灵动岛Widget的通讯方式及灵动岛Widget的布局方式。

**Comment by zhangferry** [comment]
@erduoniba 感谢推荐，下期内容会录入

**Comment by zhangferry** [comment]
已加入
