### ISSUE TITLE
AJTools-AlfredWorkflow开发常用工具集及一些自动化脚本

### ISSUE THREAD

**Issue by kaqijiang** [zhangferry/iOSWeeklyLearning#348]
## 我常用的开发工具，不断完善和更新Alfred Workflow。
目前包含一下功能。

时间戳转换
unicode转中文
随机密码
MD5
URL解析
copy SHH Key
Sublime3 打开.bash_profile
Sublime3 打开.zshrc
打开当前窗口在iTerm2中
打开当前iTerm2路径在Finder中
当前文件夹下快速新建文件
ChatGPT聊天
Jenkins启动停止重启
复制当前窗口目录
获取IP
人民币大小写转换

**Comment by zhangferry** [comment]
已经录入
