### ISSUE TITLE
分享一篇解读近期 IAP 定价规则变化的文章

### ISSUE THREAD

**Issue by SeaHub** [zhangferry/iOSWeeklyLearning#349]
## 文章标题、著名出处和作者
苹果内购录：关于新定价规则的理解与思考
本文由本人（Seahub）编写，首发于微信公众平台

## 文章链接
https://mp.weixin.qq.com/s/ZQlBFHuRoDYmYpMfgnsp2Q

## 推荐理由（如果没有可以摘抄文章内一段重要的话）
苹果 2023/03/09 发布了新的定价规则（https://developer.apple.com/cn/news/?id=dbrszv62），其中有一些修改点可能会对现有业务逻辑带来一些影响。本文对历史规则进行了回顾，同时也对新的定价规则进行了分析解读。
除此之外，推荐需要处理内购的同学可以关注一下该《苹果内购录》系列文章

**Comment by zhangferry** [comment]
已经录入
