### ISSUE TITLE
Xnip Mac上简单好用截图工具

### ISSUE THREAD

**Issue by once-liu** [zhangferry/iOSWeeklyLearning#4]
1、它叫什么名字，简单介绍
Xnip

为什么有微信或QQ的默认截图，还推荐这个？
因为好用。相比于微信或QQ的截图，还有几个好用功能
- 滚动截图
- 贴图
- 可漂浮与桌面，多桌面切换时也会存在
   在一些需要局部数据对比时尤其好用。比如服务端的接口API，截图漂浮后，可以方便的撸代码。

2、是否付费
免费

3、下载地址，提供正版下载地址（个别大型的收入网站也行，不要使用网盘）
https://zh.xnipapp.com

**Comment by zhangferry** [comment]
已采纳
