### ISSUE TITLE
Vimac App - control macOS UI with the keyboard only.

### ISSUE THREAD

**Issue by beatman423** [zhangferry/iOSWeeklyLearning#5]
## 它叫什么名字，简单介绍

**Vimac App - control macOS UI with the keyboard only.**

> 一款Mac上的键盘效率工具，通过用键盘代替鼠标操作从而提高电脑使用效率，非常适合程序员使用。
> 功能简介
> · 快捷键“Ctrl+Space”激活点击模式，输入提示字母完成鼠标单击操作，按住“Shift”键输入提示字母完成鼠标右键单击操作，按住“Command”键输入提示字母完成鼠标双击操作
> · 快捷键“Ctrl+S”激活滚动模式，使用HJKL+DU键进行滚动操作，按“TAB”键即可循环选择滚动区域

## 是否付费（如果付费的话标下价格）

免费下载 / 使用无内购

## 下载地址，提供正版下载地址（个别大型的收入网站也行，不要使用网盘） 

https://vimacapp.com

**Comment by zhangferry** [comment]
已采纳
