### ISSUE TITLE
文章分享《论证：iOS安全性，为什么需要审核？》

### ISSUE THREAD

**Issue by iHTCboy** [zhangferry/iOSWeeklyLearning#60]
## 文章标题、著名出处和作者

- 文章标题：《论证：iOS安全性，为什么需要审核？》
- 出处：掘金
- 作者：37手游iOS技术运营团队 

## 文章链接

https://juejin.cn/post/6967199105541996575

## 推荐理由（如果没有可以摘抄文章内一段重要的话）

从辩论的视角分析 iOS 安全性，同时与 macOS 安全性进行对比，提出了让 iOS 更加安全的建议，文中同时也总结了非常多 iOS 和 macOS 安全技术小知识，可以让大家在短时间里快速入门和重温 Apple OS 安全性知识点。

**Comment by zhangferry** [comment]
感谢分享，已采纳到第13期周报里。
