### ISSUE TITLE
周报第二期 推荐博客汇总

### ISSUE THREAD

**Issue by zhangferry** [zhangferry/iOSWeeklyLearning#7]
大家可以将推荐的博客或者公众号内容放到这个issue下面。

**Comment by RayLeeBoy** [comment]
应用名称: Go2Shell - 在终端中打开当前Finder目录
下载地址: https://zipzapmac.com/go2shell
安装方法: 
1. 双击下载的文件, 将Go2Shell拖入Applications目录中
2. 在Applications中, 双击打开Go2Shell, 出现下面的窗口
![main](https://user-images.githubusercontent.com/44865494/103080388-b0872500-4610-11eb-9296-b502f5cc1079.png)
3. 点击Install Go2Shell to Finder完成安装
4. 打开Finder窗口, 在工具栏中出现Go2Shell图标
5. 点击Go2Shell图标, 就会在终端中打开当前Finder目录

**Comment by zhangferry** [comment]
[GitHub 2020 报告：全球开发者工作与生活的平衡情况](https://juejin.cn/post/6908880779963695118) -- 来自掘金：LeviDing

**Comment by zhangferry** [comment]
[2020 腾讯Techo Park - Flutter与大前端的革命](https://juejin.cn/post/6908357007749693454) -- 来自掘金：恋猫de小郭
[WWDC20 iOS14 Runtime优化](https://mp.weixin.qq.com/s/opD__14wpHL06VKPtXeM4g) -- 来自公众号：知识小集

**Comment by zhangferry** [comment]
[使用 Swift 编写 CLI 工具的入门教程](https://mp.weixin.qq.com/s/V4IdsYUouKGr68ULyb88Qw) -- 来自公众号：一瓜技术
[阿里 10 年：一个普通技术人的成长之路](https://juejin.cn/post/6908569967289958408) -- 来自掘金：阿里巴巴云原生

**Comment by zhangferry** [comment]
已采纳
