### ISSUE TITLE
文章分享《揭秘苹果应用审核团队（史上最全版）》

### ISSUE THREAD

**Issue by iHTCboy** [zhangferry/iOSWeeklyLearning#72]
## 文章标题、著名出处和作者

- 文章标题：揭秘苹果应用审核团队（史上最全版）
- 出处：掘金
- 作者：37手游iOS技术运营团队 

## 文章链接

https://juejin.cn/post/6970363897668698148/

## 推荐理由（如果没有可以摘抄文章内一段重要的话）

史上最全版：揭秘苹果应用审核团队，告诉你 App Store 的由来，是怎样发展到今天这样辉煌，如何自动化：机器审核+人工审核？审核速度是怎么从7-10天，提升到如今只需要 48 小时的？

**Comment by zhangferry** [comment]
已采纳到第十四期内容
