### ISSUE TITLE
Go2Shell - 在终端中打开当前Finder目录

### ISSUE THREAD

**Issue by RayLeeBoy** [zhangferry/iOSWeeklyLearning#9]
应用名称: Go2Shell - 在终端中打开当前Finder目录
下载地址: https://zipzapmac.com/go2shell
软件状态: 免费
安装方法: 
1. 双击下载的文件, 将Go2Shell拖入Applications目录中
2. 在Applications中, 双击打开Go2Shell, 出现下面的窗口
![main](https://user-images.githubusercontent.com/44865494/103080388-b0872500-4610-11eb-9296-b502f5cc1079.png)
3. 点击Install Go2Shell to Finder完成安装
4. 打开Finder窗口, 在工具栏中出现Go2Shell图标
5. 点击Go2Shell图标, 就会在终端中打开当前Finder目录

**Comment by zhangferry** [comment]
已采纳
